name: Merge Testing
on: push
env:
  PNPTESTING_MSAL_GRAPH_CONFIG: ${{ secrets.PNPTESTING_MSAL_GRAPH_CONFIG }}
  PNPTESTING_MSAL_GRAPH_SCOPES: ${{ secrets.PNPTESTING_MSAL_GRAPH_SCOPES }}
  PNPTESTING_MSAL_SP_CONFIG: ${{ secrets.PNPTESTING_MSAL_SP_CONFIG }}
  PNPTESTING_MSAL_SP_SCOPES: ${{ secrets.PNPTESTING_MSAL_SP_SCOPES }}
  PNPTESTING_NOTIFICATIONURL: ${{ secrets.PNPTESTING_NOTIFICATIONURL }}
  PNPTESTING_SITEURL: ${{ secrets.PNPTESTING_SITEURL }} 
jobs:
  run_push_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # setup nodejs
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Run lint 
        run: npm run lint
      - name: Run package
        run: npm run package
      - name: Run tests
        run: npm test -- --mode push --cleanup --msal
